### ISSUE TITLE
Migrating from U2F

### ISSUE THREAD

**Issue by gavinwahl** [duo-labs/py_webauthn#116]
I run an RP with many keys registered using the U2F API, and now am trying to update to webauthn as the U2F api is being removed from chrome. Do you have a a guide on how to do this?

My existing registered keys have a public key in a format like `A7vTrxM6bfrFNJxSZSfKSL1LY3gcFz5TIM-VX8NZ9Et5zKdKy4sENZsdQPAPGnF2OGt9GNNYYnfj8CzyH4NKJ8`, a key handle in a format like `xMm8q_Yv30fRCDpEGmipy9WlgVr0rJHiPB9_zCg3V4_ev4wrtcEqYj4voAe_Mjjt4n78_eVlGqDdMv365N0Q4g`, and an app id in a format like `https://localhost:8000`.

1. How do these values map to the options for generate_authentication_options?
2. Is it possible to store newly-registered webauthn keys as those type of values, so I don't have to change my database schema?

This is for the open-source project https://github.com/gavinwahl/django-u2f

Thank you

**Comment by MasterKale** [comment]
@gavinwahl As a matter of fact the `appid` WebAuthn extension is specifically for use-cases like yours:

https://www.w3.org/TR/webauthn-2/#sctn-appid-extension

To start try adding the extension to the options that come out of `generate_authentication_options()`:

```py
opts = generate_authentication_options(
    # ...
    allow_credentials=[
        PublicKeyCredentialDescriptor(
            id="xMm8q_Yv30fRCDpEGmipy9WlgVr0rJHiPB9_zCg3V4_ev4wrtcEqYj4voAe_Mjjt4n78_eVlGqDdMv365N0Q4g".to_bytes()
        ),
    ],
);
opts["extensions"] = {
    "appid": "https://localhost:8000"
}
```

Once you pass those options into `navigator.credentials.get()` on the front end you should be able to call [`getClientExtensionResults()`](https://www.w3.org/TR/webauthn-2/#dom-publickeycredential-getclientextensionresults) on the returned response to get an object with an `appid` property that tells you if a U2F credential was used, something like this:

```js
const resp = await navigator.credentials.get(opts);
const clientExtensionResults = resp.getClientExtensionResults();
console.log(clientExtensionResults); // { appid: true }
```

If you get `true` here then when you verify this response you'll want to pass in `"https://localhost:8000"` for `expected_rp_id` when you call `verify_authentication_response()`

This is all from memory (I worked with a colleague recently that went through this with py_webauthn) so I apologize if you dive into this and it turns out I glossed over too much. Let me know if you run into any issues and I can try to help further.

**Comment by MasterKale** [comment]
Ah, I neglected to respond to one of your questions:

> 2. Is it possible to store newly-registered webauthn keys as those type of values, so I don't have to change my database schema?

When your users register newer WebAuthn credential IDs, a credential's ID and corresponding public key will come out of `verify_registration_response()` as `bytes` which you're free to serialize and store as you see fit - I don't see why those couldn't slot into your existing credentials table. The one thing that would likely prevent you from using your U2F-centric table structure as-is would be due to needing to store and update a corresponding [`signCount`](https://www.w3.org/TR/webauthn-2/#signcount), a value that can help with preventing "cloned authenticator" attacks.

If your authentication security model allows it then I suppose you could ignore sign count and always pass `0` for `credential_current_sign_count` when you call `verify_authentication_response()`, and then there'd be no need to change your DB table structure.

> This is for the open-source project https://github.com/gavinwahl/django-u2f

Looking at your Django models, specifically `U2FKey`, I'd map values accordingly:

```py
verification = verify_registration_response(expected_rp_id=expected_rp_id, **kwargs)

new_key = U2FKey(
    public_key=verification.credential_public_key,
    key_handle=verification.credential_id,
    app_id=expected_rp_id
)
```

That'd probably be sufficient to store WebAuthn credentials without making changes to your model.

**Comment by gavinwahl** [comment]
This helps so much! Thank you!

In your call to PublicKeyCredentialDescriptor, you're passing a string to id, but it requires bytes. It should be passed through base64url_to_bytes instead right?

**Comment by MasterKale** [comment]
> In your call to PublicKeyCredentialDescriptor, you're passing a string to id, but it requires bytes. It should be passed through base64url_to_bytes instead right?

I did a bit of handwaving there because I didn't want to assume your encoding, but yes, if you store your `key_handle` as base64url then you can safely pass that through `base64url_to_bytes` when assigning to `PublicKeyCredentialDescriptor`'s `id` on that line :v:

**Comment by gavinwahl** [comment]
Got this all working, thank you very much!
